const frames=async(n=2)=>{for(let i=0;i<n;i++)await new Promise(requestAnimationFrame);};
const key=code=>document.dispatchEvent(new KeyboardEvent('keydown',{code,bubbles:true}));
export async function checkExploration(h){
  const checks=[],assert=(value,label)=>{if(!value)throw new Error(label);checks.push(label);console.log('EXPLORATION_CHECK '+label);};
  assert(h.state().mode==='playing','Exploration starts directly in play');
  assert(!window.__AZHORA__&&!window.azhoraRoadStorage,'Legacy game and adventure save bridge are absent');
  assert(!document.getElementById('quest-title')&&!document.getElementById('skills-sheet'),'No quest or skill interface');
  assert(h.state().cells.length===1,'Only the starting hex is discovered');
  const start=h.state().position;h.hold('KeyS',true);for(let i=0;i<30;i++)h.step(.04);h.hold('KeyS',false);
  assert(Math.hypot(h.state().position[0]-start[0],h.state().position[2]-start[2])>.5,'Walking moves through the real Minora world');
  const floor=h.state().position[1];assert(h.jump(),'Jump starts');h.step(.04);assert(h.state().position[1]>floor,'Jump lifts the character');for(let i=0;i<50;i++)h.step(.04);assert(h.state().grounded,'Jump lands');
  const beforeCamera=h.state().camera.distance;document.getElementById('exploration-canvas').dispatchEvent(new WheelEvent('wheel',{deltaY:100}));assert(h.state().camera.distance>beforeCamera,'Mouse wheel changes follow camera distance');
  key('Escape');assert(h.state().mode==='pause','Escape pauses');const paused=h.state().position;h.hold('KeyW',true);h.step(.04);assert(JSON.stringify(h.state().position)===JSON.stringify(paused),'Pause stops movement');key('Escape');
  key('KeyM');await frames(4);assert(h.state().mode==='map','M opens the existing map');assert(h.state().map.campaign.view==='regions','The map defaults to Regions');assert(document.getElementById('atlas-loading').hidden,'Map drawing and metadata loaded');
  document.querySelector('[data-atlas-view="geopolitical"]').click();assert(!document.querySelector('[data-info-tab="quests"]'),'Exploration political map has no quest tab');
  assert(h.state().character==='teresod','Exploration starts as Teresod');assert(h.state().map.chart.reveal===true,'Explore the World starts with the full atlas');assert(h.state().map.campaign.knownRegions.length===132,'Full political map is available');
  h.reveal(true);assert(h.state().map.campaign.knownRegions.length===132,'Developer reveal exposes the whole map');h.reveal(false);assert(h.state().map.campaign.knownRegions.length<132,'Turning reveal off restores fog');
  key('KeyM');await h.visit({x:-2070,z:345});await frames();assert(h.state().cells.length>1,'Visiting another region loads it and records discovery');
  key('F8');assert(h.state().mode==='developer','F8 opens developer tools');
  const select=document.getElementById('developer-region');
  assert(select.options.length===132&&[...select.options].filter(o=>!o.disabled).length===117,'Dropdown lists all 132 atlas regions and 117 playable destinations');
  const reveal=document.getElementById('developer-reveal'),discovered=h.state().cells.length;
  reveal.click();assert(h.state().map.campaign.knownRegions.length===132&&document.getElementById('reveal-all').checked,'Developer panel reveals the full geopolitical map');
  assert(h.state().cells.length===discovered,'Reveal does not grant permanent discoveries');
  document.getElementById('developer-map').click();await frames(3);assert(h.state().mode==='map','Developer panel opens the map');
  document.getElementById('reveal-all').click();assert(!reveal.checked&&h.state().map.campaign.knownRegions.length<132,'Map and panel reveal switches stay synchronized');
  key('F8');select.value='106';document.getElementById('developer-go').click();
  const deadline=performance.now()+180000;while(h.state().mode==='loading'&&performance.now()<deadline)await frames();
  assert(h.state().mode==='playing'&&h.state().region===106,'Dropdown Go loads and teleports to West Ithzel');
  const clickMount=name=>{h.openDeveloper();document.querySelector(`[data-exploration-mount="${name}"]`).click();};
  clickMount('horse');assert(h.state().mount.kind==='horse'&&h.state().mount.visible.join()==='horse','Developer horse mounts and renders');
  const horseStart=h.state().position;h.hold('KeyW',true);h.hold('ShiftLeft',true);for(let i=0;i<10;i++)h.step(.04);h.hold('KeyW',false);h.hold('ShiftLeft',false);
  assert(Math.hypot(h.state().position[0]-horseStart[0],h.state().position[2]-horseStart[2])>1,'Developer horse canters through the world');
  key('KeyG');assert(h.state().mount.kind==='foot','G dismounts the horse');
  clickMount('bat');assert(h.state().mount.kind==='bat'&&!h.state().grounded,'Developer bat takes flight');
  const beforeLift=h.state().position[1];h.hold('Space',true);for(let i=0;i<8;i++)h.step(.04);h.hold('Space',false);assert(h.state().position[1]>beforeLift+4,'Space climbs while flying');
  assert(!h.save().ok,'Airborne position cannot overwrite a ground checkpoint');
  const flying=h.state().position;clickMount('dragon');assert(h.state().mount.kind==='dragon'&&h.state().mount.visible.join()==='dragon','Developer dragon replaces the bat');
  assert(Math.abs(h.state().position[1]-flying[1])<.01,'Switching flying mounts preserves altitude');
  h.pause();const held=h.state().position;h.hold('KeyW',true);h.step(.04);assert(JSON.stringify(h.state().position)===JSON.stringify(held),'Pause freezes developer flight');h.resume();
  key('KeyG');for(let i=0;i<40;i++)h.step(.04);assert(h.state().mount.kind==='foot'&&h.state().grounded,'G lands the dragon on dry ground');
  clickMount('dragon');assert(await h.travelToRegion(13),'Teleport works while airborne');assert(h.state().mount.kind==='foot'&&!h.state().mount.visible.length&&h.state().region===13,'Teleport ends flight and arrives on foot');
  clickMount('horse');
  key('F5');assert(h.store.read().ok&&h.store.read().data.cells.length>1,'F5 saves position and discoveries');const saved=h.snapshot();
  h.hold('KeyS',true);for(let i=0;i<20;i++)h.step(.04);h.hold('KeyS',false);await h.loadSaved();
  assert(Math.hypot(h.state().position[0]-saved.position.x,h.state().position[2]-saved.position.z)<.01,'Load restores the saved position');
  assert(h.state().mount.kind==='foot','Loading a mounted save restores safely on foot');
  assert(!h.state().frameErrors.length,'No frame errors');
  const resources=performance.getEntriesByType('resource').map(r=>new URL(r.name).pathname);
  for(const file of ['/src/main.js','/src/app/saves/road-checkpoint.js','/src/gameplay/combat/combat.js'])assert(!resources.includes(file),'Not requested: '+file);
  assert((await fetch('/reference-private/unavailable.txt')).status===403,'Private reference paths cannot be served');
  assert((await fetch('/saves/road-checkpoint.json')).status===403,'Save files cannot be served');
  return {checks,saved,readyMs:h.state().readyMs,resources:resources.length};
}
export async function checkExplorationReload(h,saved){
  const checks=[],assert=(value,label)=>{if(!value)throw new Error(label);checks.push(label);};
  assert(Math.hypot(h.state().position[0]-saved.position.x,h.state().position[2]-saved.position.z)<.01,'Fresh renderer restores the saved position');
  assert(JSON.stringify(h.state().cells)===JSON.stringify(saved.cells),'Fresh renderer preserves discoveries');
  assert(h.state().camera.distance===saved.camera.distance,'Fresh renderer restores the camera');
  h.openMap();await frames(3);assert(h.state().map.chart.reveal,'Explore the World restores with the full atlas available');h.resume();
  assert(!h.state().frameErrors.length,'Reload reports no frame errors');
  return {checks,readyMs:h.state().readyMs};
}
