import {encounterKeys} from './encounter-controls.js';
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
export async function checkLizeem(h){
  const checks=[],assert=(value,label)=>{if(!value)throw Error(label);checks.push(label);};
  const state=()=>h.state(),click=id=>document.getElementById(id).click();
  const choose=id=>{const select=document.getElementById('selected-region');select.value=id;select.dispatchEvent(new Event('change'));};
  assert(state().campaign.day===0&&!state().running,'Starts paused on day zero');
  assert(Object.keys(state().map.owners).length===5,'Only five regions appear on the existing atlas');
  assert(state().map.owners.isareos==='minora','Minora starts neutral in Isareos');
  assert(document.getElementById('reinforce').disabled,'Neutral Minora cannot receive a war intervention');
  document.querySelector('[data-view="regions"]').click();assert(state().map.layer==='regions','Regions view works');
  document.querySelector('[data-view="geopolitical"]').click();assert(state().map.layer==='geopolitical','Geopolitical view works');
  click('advance');assert(state().campaign.day===1&&state().baseline.day===1,'Advance steps both runs by exactly one day');
  assert(state().map.armies>0&&document.querySelectorAll('[data-army]').length===state().campaign.armies.length,'Marching armies are drawn from simulation state');
  const marker=document.querySelector('[data-army]');marker.focus();marker.dispatchEvent(new KeyboardEvent('keydown',{code:'Enter',bubbles:true}));
  const armyId=state().selectedArmy,army=state().campaign.armies.find(a=>a.id===armyId);
  assert(armyId&&document.getElementById('army-inspector').open,'Army markers can open the inspector by keyboard');
  assert(document.getElementById('army-detail').textContent.includes(army.name),'Inspector identifies the persistent army');
  assert(/distance.*terrain.*crossing/.test(document.getElementById('army-detail').textContent),'Inspector explains travel cost and arrival time');
  assert(document.getElementById('army-detail').textContent.includes('Exposed frontier'),'Inspector explains why the army chose its target');
  h.advance(4);
  assert(state().selectedArmy===armyId&&state().campaign.armies.find(a=>a.id===armyId).status==='recovering','Selection follows the same army into recovery');
  assert(document.getElementById('army-detail').textContent.includes('Battle losses'),'Inspector shows the selected army battle report');
  const beforeRun=state().campaign.day;
  const speed=document.getElementById('speed');speed.value='100';speed.dispatchEvent(new Event('change'));click('play');await wait(360);click('play');
  assert(state().campaign.day>=beforeRun+2&&!state().running,'Run, speed and pause controls advance time');
  const paused=state().campaign.day;await wait(220);assert(state().campaign.day===paused,'Pause stops campaign time');
  const beforeZoom=state().map.viewBox.w;document.getElementById('scenario-map').dispatchEvent(new WheelEvent('wheel',{deltaY:-100,cancelable:true}));assert(state().map.viewBox.w<beforeZoom,'Map zoom works');click('fit-map');
  h.reset(1731);h.advance(100);const baseline=state().campaign;
  assert(baseline.winner==='east','Unattended default scenario resolves to an East victory');
  assert(state().map.owners.ovesos==='east'&&state().map.owners.nethereum==='east','Conquests update actual geopolitical territory');
  h.reset(1731);h.advance(100);assert(JSON.stringify(state().campaign)===JSON.stringify(baseline),'Reset reproduces the full same-seed history');
  h.reset(1731);choose('ovesos');click('reinforce');
  assert(state().campaign.regions.ovesos.garrison===125&&state().baseline.regions.ovesos.garrison===45,'Developer reinforcement changes only the intervention run');
  h.advance(4);const exported=h.exportRun(),saved=JSON.stringify(state().campaign);h.reset(1);h.importRun(exported);
  assert(JSON.stringify(state().campaign)===saved,'Export/import replay restores the complete state');
  const before=JSON.stringify(state().campaign);let rejected=false;try{h.importRun({...exported,version:99});}catch{rejected=true;}
  assert(rejected&&JSON.stringify(state().campaign)===before,'Invalid imports preserve the current experiment');
  rejected=false;try{h.importRun({...exported,scenario:'lizeem-east-west-v1'});}catch{rejected=true;}assert(rejected&&JSON.stringify(state().campaign)===before,'Old scenario exports are rejected without changing the current run');
  h.advance(100);assert(!document.getElementById('finish-baseline').hidden,'Earlier intervention victory offers a baseline completion control');const won=JSON.stringify(state().campaign);click('finish-baseline');assert(JSON.stringify(state().campaign)===won,'Completing baseline leaves the intervention result untouched');assert(state().campaign.winner==='west'&&state().baseline.winner==='east','Intervention changes the winner compared with its untouched baseline');
  assert(state().map.owners.isareos==='minora','Neutral territory survives both outcomes');
  assert(document.getElementById('play').disabled&&document.getElementById('advance').disabled,'Resolved war stops the clock');
  assert(document.getElementById('comparison').querySelectorAll('.changed').length===4,'Comparison identifies all four territories changed by intervention');
  const resources=performance.getEntriesByType('resource').map(r=>new URL(r.name).pathname);
  assert(!resources.some(p=>p.includes('three')||p==='/src/world.js'||p==='/src/main.js'||p.includes('/content/quests/')||p.includes('/gameplay/skills/')),'No 3D world, old game, quests or skills are loaded');
  assert((await fetch('/reference-private/unavailable.txt')).status===403,'Private reference paths are not served');
  assert((await fetch('/saves/road-checkpoint.json')).status===403,'Adventure saves are not served');
  const baselineWinner=state().baseline.winner,interventionWinner=state().campaign.winner;
  const beginHero=()=>{
    h.reset(1731);const destination=document.getElementById('hero-destination');destination.value='caricas';click('hero-travel');click('hero-watch');h.advance(100);
  };
  beginHero();
  assert(state().campaign.day===9&&state().campaign.pending?.region==='caricas','Traveling to Caricas offers the actual local battle on day nine');
  assert(state().campaign.hero.region==='caricas'&&!state().campaign.hero.journey,'Hero arrives before being offered a battle');
  assert(document.querySelector('.hero-label').textContent.includes('Teresod'),'Map renders the hero from campaign state');
  assert(!state().running&&document.getElementById('play').disabled&&document.getElementById('advance').disabled,'Pending battle stops the campaign clock and disables stepping');
  const pendingExport=h.exportRun(),pending=JSON.stringify(state().campaign);h.reset(1);h.importRun(pendingExport);
  assert(JSON.stringify(state().campaign)===pending,'Export and import preserve an unresolved local battle');
  click('hero-encounter');assert(document.getElementById('encounter-dialog').open,'Local battle opens an accessible decision dialog');
  click('encounter-return');assert(!state().campaign.pending&&state().campaign.regions.caricas.owner==='east','Staying out resolves the same automatic battle');
  beginHero();click('hero-encounter');click('fight-attacker');
  const waitFor=async(fn,label,ms=20000)=>{const end=performance.now()+ms;while(!fn()&&performance.now()<end)await wait(50);assert(fn(),label);};
  await waitFor(()=>!!state().hero.encounter,'Joining lazily loads the playable 3D encounter');
  const canvas=document.getElementById('encounter-canvas');canvas.focus();window.dispatchEvent(new Event('focus'));
  canvas.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyA',bubbles:true}));await wait(150);canvas.dispatchEvent(new KeyboardEvent('keyup',{code:'KeyA',bubbles:true}));
  assert(state().hero.encounter.hero.x<0,'Movement input moves the playable hero');
  canvas.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',bubbles:true}));await wait(60);canvas.dispatchEvent(new KeyboardEvent('keyup',{code:'Space',bubbles:true}));
  assert(state().hero.encounter.hero.dodgeCooldown>0&&!state().running,'Dodge input works without starting the campaign clock');
  const combatDeadline=performance.now()+30000;
  while(!state().hero.result&&performance.now()<combatDeadline){
    for(const [code,down] of Object.entries(encounterKeys(state().hero.encounter)))canvas.dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{code,bubbles:true}));
    await wait(16);
  }
  for(const code of Object.keys(encounterKeys(null)))canvas.dispatchEvent(new KeyboardEvent('keyup',{code,bubbles:true}));
  assert(!!state().hero.result,'Playable combat reaches a result using movement, dodge and strike inputs');
  assert(state().hero.result==='success','Defeating the three guards produces success');
  assert(state().campaign.day===9&&!!state().campaign.pending,'Combat does not advance or mutate the campaign before submission');
  click('encounter-return');
  assert(!document.getElementById('encounter-dialog').open&&!state().campaign.pending,'Returning disposes the encounter and resolves the pending battle');
  assert(state().campaign.regions.caricas.owner==='west'&&state().map.owners.caricas==='west','Hero success changes the actual conquest and geopolitical map');
  assert(state().baseline.regions.caricas.owner==='east','Untouched comparison retains its original outcome');
  assert(state().campaign.commands.filter(c=>c.type==='hero-result').length===1,'The hero result is recorded exactly once');
  const played=h.exportRun(),playedState=JSON.stringify(state().campaign);h.reset(1);h.importRun(played);assert(JSON.stringify(state().campaign)===playedState,'Played combat outcome replays without rerunning the 3D encounter');
  beginHero();click('hero-encounter');click('fight-defender');await waitFor(()=>!!state().hero.encounter,'Another encounter can be opened after disposal');window.dispatchEvent(new Event('focus'));
  await waitFor(()=>!!state().hero.result,'Taking enemy strikes reaches defeat');assert(state().hero.result==='defeat','Defeat is a real playable result');
  document.getElementById('encounter-dialog').dispatchEvent(new Event('cancel',{cancelable:true}));
  assert(state().campaign.commands.at(-1).outcome==='defeat','Escape after defeat applies defeat instead of discarding it');
  const heroResources=performance.getEntriesByType('resource').map(r=>new URL(r.name).pathname);
  assert(heroResources.some(p=>p.includes('/vendor/three'))&&!heroResources.some(p=>p==='/src/world.js'||p==='/src/main.js'||p.includes('/content/quests/')||p.includes('/gameplay/skills/')),'The arena reuses character models without loading the world, quests or skills');
  h.reset(1731);choose('ovesos');click('reinforce');h.advance(100);click('finish-baseline');
  for(const d of document.querySelectorAll('details'))d.open=d.querySelector('summary').textContent.includes('Compare');
  return {checks,readyMs:state().readyMs,baselineWinner,interventionWinner,resources,heroResources};
}
