import {parseCells,unionCells} from './geometry.js';

export async function runChecks(){
  const $=id=>document.getElementById(id),ui=window.campaignUIPreview,checks=[];
  const check=(value,label)=>{if(!value)throw Error(label);checks.push(label);};
  const click=selector=>{const button=document.querySelector(`button${selector}`);if(!button)throw Error(`Missing ${selector}`);button.click();};
  const view=layer=>click(`[data-layer="${layer}"]`);
  const showSample=value=>{$('preview-tools').click();$('sample').value=value;$('apply-sample').click();};
  const labelCount=id=>document.querySelectorAll(`.country-label[data-faction="${id}"]`).length;
  check(ui.ready&&ui.getState().regionCount===132,'Existing atlas loads all 132 regions');
  check(ui.getState().layer==='regions','Opening view preserves the normal regional map');
  view('geopolitical');
  check(!document.querySelector('.modes,.clock,.chronicle,[data-action="aid"],#play'),'No mode tabs, timeline, clock or command controls');
  check(document.querySelectorAll('.hit').length===132,'Regions remain selectable in every view');
  check(getComputedStyle(document.querySelector('#region-labels')).display==='none','Geopolitical view hides region names');
  check(getComputedStyle(document.querySelector('#region-boundaries')).display==='none','Geopolitical view hides internal region borders');
  const lond=ui.getTerritory('stonefist-lond');
  check(lond.regions.length===5&&labelCount('stonefist-lond')===1,'Lond combines five regions under one faction label');
  const sumRegionEdges=lond.regions.reduce((n,name)=>n+unionCells(parseCells(document.querySelector(`.hit[data-region="${name}"]`).getAttribute('d'))).edgeCount,0);
  check(lond.edgeCount<sumRegionEdges,'Merged country outline removes shared regional edges');
  const area=p=>p.reduce((sum,a,i)=>{const b=p[(i+1)%p.length];return sum+a[0]*b[1]-b[0]*a[1];},0)/2;
  const cellArea=lond.cells.reduce((sum,c)=>sum+Math.abs(area(c)),0),outlineArea=Math.abs(lond.loops.reduce((sum,l)=>sum+area(l),0));
  check(Math.abs(cellArea-outlineArea)<.01,'Country union preserves exact authored land area');
  view('regions');check(getComputedStyle(document.querySelector('#region-labels')).display!=='none'&&getComputedStyle(document.querySelector('#region-boundaries')).display!=='none','Regions restores names and boundaries');
  check($('country-labels').hidden,'Regions view hides faction labels');
  view('stability');check(!$('stability-key').hidden&&getComputedStyle(document.querySelector('#region-labels')).display!=='none','Stability retains regional names and displays its key');
  check(document.querySelector('.hit[data-region="Drent"]').getAttribute('fill')!==document.querySelector('.hit[data-region="East Lotharn Mountains"]').getAttribute('fill'),'Stable provinces and open rebellion have different colors');
  view('geopolitical');
  $('search').value='Lond';$('search').dispatchEvent(new Event('input'));$('search').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
  check(ui.getState().faction==='stonefist-lond'&&$('detail-content').textContent.includes('5 regions'),'Keyboard search opens faction and territory information');
  const oldUndead=ui.getTerritory('eshtor-undead').path;
  showSample('north-riesov');
  check(ui.ownerOf('North Riesov')==='eshtor-undead','Sample conquest changes the regional controller');
  check(ui.getTerritory('eshtor-undead').regions.length===2&&labelCount('eshtor-undead')===1,'Undeadland combines Eshtor and North Riesov under one label');
  check(ui.getTerritory('eshtor-undead').path!==oldUndead&&ui.getTerritory('riesov').regions.length===1,'Conquest rebuilds both countries’ geometry');
  const fill=document.querySelector('.country-shape[data-faction="eshtor-undead"]').getAttribute('fill');
  check(fill&&document.querySelector('.hit[data-region="North Riesov"]').dataset.owner==='eshtor-undead','Map ownership and country fill use the same snapshot');
  view('regions');check(ui.ownerOf('North Riesov')==='eshtor-undead','Changing views preserves the sample control state');
  view('geopolitical');showSample('east-lond');
  check(ui.getTerritory('stonefist-lond').regions.length===4&&!ui.getTerritory('stonefist-lond').regions.includes('East Lond'),'Lost East Lond is removed from Lond’s four-region territory');
  check(ui.getTerritory('stonefist-lond').path!==lond.path&&labelCount('stonefist-lond')===1,'Lond outline and its single label update after territory loss');
  click('[data-tab="factions"]');check(document.querySelectorAll('[data-faction].faction-row').length===46,'Read-only factions browser retains all 46 actors');
  click('[data-faction="north-gorgi-goblins"].faction-row');check(!$('detail-content').textContent.includes('Thalmagar'),'Territorial inspection does not expose a secret overlord');
  showSample('opening');
  ui.selectFaction('ambroni-empire');
  check($('detail-content').textContent.includes('Willard')&&$('detail-content').textContent.includes('Feradom'),'Ambron profile shows its ruler and established alliances');
  const ambronOpening=ui.getTerritory('ambroni-empire').path,izolOpening=ui.getTerritory('izol').path;
  click('[data-chapter="empire"]');
  check(ui.getState().tab==='quests'&&$('detail-content').textContent.includes('Hadric Venmor')&&$('detail-content').textContent.includes('Solis, taken'),'Country links to the existing Chapter 1 monarchist path');
  view('regions');click('[data-snapshot="chapter-monarchy"]');
  check(ui.getState().layer==='geopolitical','Previewing a successful ending shows its political border change');
  check(ui.ownerOf('West Suval')==='ambroni-empire'&&ui.ownerOf('Moros Plain')==='ambroni-empire','Monarchist success gains West Suval and retains Moros');
  check(!ui.getTerritory('west-suval')&&ui.getTerritory('ambroni-empire').path!==ambronOpening,'Monarchist victory merges West Suval into Ambron geometry');
  check($('detail-content').textContent.includes('Successful ending'),'Quest panel acknowledges the displayed successful ending');
  ui.selectFaction('west-suval');check($('detail-content').textContent.includes('Solis has fallen')&&$('detail-content').textContent.includes('0 regions'),'Displaced West Suval faction stays inspectable without territory');
  click('[data-tab="quests"]');click('[data-chapter="coalition"]');
  check($('detail-content').textContent.includes('Tulle Barr')&&$('detail-content').textContent.includes('Izolveth'),'Coalition route retains its established final report');
  click('[data-snapshot="chapter-coalition"]');
  check(ui.ownerOf('Moros Plain')==='izol'&&ui.ownerOf('West Suval')==='west-suval','Coalition success assigns Moros to Izol and preserves distinct West Suval');
  check(ui.getTerritory('izol').regions.length===3&&ui.getTerritory('izol').path!==izolOpening&&!ui.getTerritory('ambroni-empire').regions.includes('Moros Plain'),'Coalition outcome rebuilds both losing and gaining countries');
  view('stability');check(document.querySelector('.hit[data-region="Moros Plain"]').dataset.owner==='izol','Stability shares the Chapter 1 ownership result');
  click('[data-region="Moros Plain"]');check($('detail-content').textContent.includes('Recently conquered'),'New conquest is not presented as immediate stability');
  click('[data-chapter="overview"]');check($('detail-content').textContent.includes('The Border War')&&!$('detail-content').textContent.includes('The Divided Island'),'Regional quest link uses Chapter 1, not northern examples');
  view('geopolitical');
  showSample('opening');check(ui.getTerritory('stonefist-lond').regions.length===5&&ui.getTerritory('eshtor-undead').regions.length===1,'Opening snapshot restores original boundaries');
  check(ui.ownerOf('Moros Plain')==='ambroni-empire'&&ui.ownerOf('West Suval')==='west-suval'&&ui.getTerritory('izol').regions.length===2,'Opening restores both Chapter 1 territories');
  check(['Cudon','Lesser Oremindi Mountains'].every(n=>ui.ownerOf(n)==='thalmagars-empire'),'Thalmagar owns both newly assigned opening regions');
  check(!Object.keys(localStorage).length,'No game storage is written');
  return checks;
}
