// GENERATED by scripts/build-region-rivers.mjs from the World Builder map's river edges.
// Do not edit by hand; tests/pueth-world.test.js checks it against the map.
export const RIVER_SOURCE = Object.freeze({ map: 'world-builder/map/resources/examples/azhora.wwmap', sha256: 'b36c32babaf85213a93459c87eeabe79455268db714681f88444831a221588df',
  regions: Object.freeze(["Pueth"]), edgeCount: 12 });

/** Every authored river edge on or inside the regions above: the hex pair it runs between, and its size. */
export const RIVER_EDGES = Object.freeze([
  Object.freeze({ a: Object.freeze([13,104]), b: Object.freeze([14,103]), size: 'small', regions: Object.freeze(["Drent", "Pueth"]) }),
  Object.freeze({ a: Object.freeze([14,103]), b: Object.freeze([14,104]), size: 'small', regions: Object.freeze(["Pueth", "Drent"]) }),
  Object.freeze({ a: Object.freeze([14,104]), b: Object.freeze([15,103]), size: 'small', regions: Object.freeze(["Drent", "Pueth"]) }),
  Object.freeze({ a: Object.freeze([14,104]), b: Object.freeze([15,104]), size: 'small', regions: Object.freeze(["Drent", "Pueth"]) }),
  Object.freeze({ a: Object.freeze([14,105]), b: Object.freeze([15,104]), size: 'small', regions: Object.freeze(["Drent", "Pueth"]) }),
  Object.freeze({ a: Object.freeze([14,105]), b: Object.freeze([15,105]), size: 'small', regions: Object.freeze(["Drent", "Pueth"]) }),
  Object.freeze({ a: Object.freeze([14,106]), b: Object.freeze([15,105]), size: 'small', regions: Object.freeze(["Drent", "Pueth"]) }),
  Object.freeze({ a: Object.freeze([16,100]), b: Object.freeze([17,100]), size: 'small', regions: Object.freeze(["Pueth", "Feradom"]) }),
  Object.freeze({ a: Object.freeze([16,101]), b: Object.freeze([17,100]), size: 'small', regions: Object.freeze(["Pueth", "Feradom"]) }),
  Object.freeze({ a: Object.freeze([16,101]), b: Object.freeze([17,101]), size: 'small', regions: Object.freeze(["Pueth", "Feradom"]) }),
  Object.freeze({ a: Object.freeze([16,102]), b: Object.freeze([17,101]), size: 'small', regions: Object.freeze(["Pueth", "Feradom"]) }),
  Object.freeze({ a: Object.freeze([17,101]), b: Object.freeze([17,102]), size: 'small', regions: Object.freeze(["Feradom", "Pueth"]) }),
]);
